### ISSUE TITLE
An issue with two typos

### ISSUE THREAD

**Issue by pedrovereza** [CocoaPods/peril-settings#3]
After checking the regex, I feel that only the first match of CocoaPods will be replaced. 
Will this one be replaced as well: CocoaPods?

**Comment by orta** [comment]
Hah - nope! :D

Think I need a `/g`.

Event: ` 1d1cda10-84fa-11e7-8123-2b01158e242a`

**Comment by orta** [comment]
Now it does thanks to https://github.com/CocoaPods/peril-settings/commit/b7ce93c5215b7b2cf4affd689feda1272fd8b6f8

**Comment by pedrovereza** [comment]
@orta Awesome! I also noticed some occurrences of `cocoapods` in the CocoaPods repo. Would it make sense to change the regex to replace both terms? I guess the only concern is that it could also replace links (like www.CocoaPods.org)

**Comment by orta** [comment]
Yeah, I feel like there's a good use for lowercase (the CLI tool is that, so it would change terminal output) the lowercase P is always a mistake IMO

**Comment by pedrovereza** [comment]
Makes sense 👍
